title: Kody Wu — Photography
email: kodeoffun@gmail.com
description: >-
  Photography portfolio for Kody Wu.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
